In [2]:
import numpy as np
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('input_game.csv')

df['p1_action'] = df['p1_action'].replace({'TRUST': 0, 'CHEAT': 1})
df['p2_action'] = df['p2_action'].replace({'TRUST': 0, 'CHEAT': 1})

df

        game_id  p1_id  p2_id  p1_action  p2_action  turn
0             0    174    125          0          1     1
1             0    174    125          1          0     2
2             0    174    125          0          0     3
3             0    174    125          0          0     4
4             0    174    125          0          0     5
...         ...    ...    ...        ...        ...   ...
180401     3014    157    169          1          0    64
180402     3014    157    169          1          0    65
180403     3014    157    169          1          0    66
180404     3014    157    169          1          0    67
180405     3014    157    169          1          0    68

[180406 rows x 6 columns]

In [3]:
def longest_common_prefix(*series):
    if not series:
        return ""

    prefix = series[0]
    for s in series[1:]:
        i = 0
        while i < len(prefix) and i < len(s) and prefix.iloc[i] == s.iloc[i]:
            i += 1
        prefix = prefix.iloc[:i]

    return prefix

player_prefix_dict = {}

for player_id in range(201):
    
    lcp = pd.Series()
    temp = df[df['p1_id'] == player_id]

    for game_id in range(3014):
        game_data1 = temp[temp['game_id'] == game_id]

        if(game_data1.empty):
            continue

        if(lcp.empty):
            lcp = game_data1['p1_action']
        else:
            lcp = longest_common_prefix(lcp, game_data1['p1_action'])

    temp = df[df['p2_id'] == player_id]
    for game_id in range(3014):
        game_data2 = temp[temp['game_id'] == game_id]

        if(game_data1.empty):
            continue

        if(lcp.empty):
            lcp = game_data1['p2_action']
        else:
            lcp = longest_common_prefix(lcp, game_data1['p2_action'])


    player_prefix_dict[player_id] = lcp
   

print(player_prefix_dict)

{0: Series([], dtype: object), 1: 21606    1
Name: p1_action, dtype: int64, 2: 103310    0
103311    0
Name: p1_action, dtype: int64, 3: 6889    0
Name: p1_action, dtype: int64, 4: 11569    1
11570    1
11571    1
11572    1
11573    1
Name: p1_action, dtype: int64, 5: 5723    1
Name: p1_action, dtype: int64, 6: 46261    0
46262    0
Name: p1_action, dtype: int64, 7: 1894    1
Name: p1_action, dtype: int64, 8: 167074    0
167075    0
167076    0
167077    1
167078    0
167079    0
167080    0
167081    1
167082    0
167083    0
167084    0
167085    1
167086    0
Name: p1_action, dtype: int64, 9: 69782    0
69783    0
69784    0
69785    0
69786    0
69787    0
69788    0
69789    0
69790    0
69791    0
69792    0
69793    0
69794    0
69795    0
Name: p1_action, dtype: int64, 10: 123660    1
123661    0
123662    0
123663    0
123664    0
123665    1
123666    1
123667    1
123668    1
123669    0
123670    1
123671    1
123672    1
123673    1
123674    0
123675    0
123676    0
123677    0
123678    1
123679    1
123680    1
123681    1
123682    1
123683    1
123684    1
123685    0
123686    0
123687    0
123688    0
123689    0
123690    1
123691    1
123692    1
123693    1
123694    0
123695    0
123696    0
123697    1
123698    1
123699    1
123700    1
123701    0
123702    0
123703    0
123704    0
123705    1
123706    1
123707    0
123708    1
123709    1
123710    1
Name: p1_action, dtype: int64, 11: 43939    1
43940    0
Name: p1_action, dtype: int64, 12: Series([], Name: p1_action, dtype: int64), 13: 24362    0
24363    0
24364    0
24365    0
Name: p1_action, dtype: int64, 14: 113429    0
Name: p1_action, dtype: int64, 15: 46414    1
46415    1
46416    1
46417    1
46418    1
Name: p1_action, dtype: int64, 16: 80760    0
Name: p1_action, dtype: int64, 17: 71860    0
71861    1
71862    1
Name: p1_action, dtype: int64, 18: 18656    0
Name: p1_action, dtype: int64, 19: 116884    1
Name: p1_action, dtype: int64, 20: 10048    0
Name: p1_action, dtype: int64, 21: 22988    1
22989    1
22990    1
Name: p1_action, dtype: int64, 22: 157106    0
Name: p1_action, dtype: int64, 23: 16173    0
Name: p1_action, dtype: int64, 24: 174830    1
174831    1
Name: p1_action, dtype: int64, 25: 7704    1
7705    1
Name: p1_action, dtype: int64, 26: Series([], Name: p1_action, dtype: int64), 27: 65767    1
Name: p1_action, dtype: int64, 28: 1229    1
1230    0
1231    0
1232    0
1233    0
1234    1
1235    1
1236    1
1237    1
Name: p1_action, dtype: int64, 29: Series([], Name: p1_action, dtype: int64), 30: 124530    0
124531    0
124532    0
Name: p1_action, dtype: int64, 31: 1328    0
1329    0
Name: p1_action, dtype: int64, 32: 147928    1
147929    1
Name: p1_action, dtype: int64, 33: 12046    1
12047    1
12048    1
12049    1
12050    1
12051    1
12052    1
12053    1
12054    1
12055    1
12056    1
Name: p1_action, dtype: int64, 34: 117126    0
117127    0
117128    0
117129    0
117130    0
         ..
117193    1
117194    1
117195    1
117196    1
117197    1
Name: p1_action, Length: 72, dtype: int64, 35: 2906    0
Name: p1_action, dtype: int64, 36: 33054    0
33055    1
Name: p1_action, dtype: int64, 37: 13711    0
Name: p1_action, dtype: int64, 38: 9113    0
Name: p1_action, dtype: int64, 39: 156934    1
Name: p1_action, dtype: int64, 40: 177008    0
177009    0
177010    1
177011    0
177012    1
177013    0
177014    0
177015    1
177016    1
177017    0
177018    1
177019    0
177020    1
177021    1
177022    0
177023    0
177024    0
177025    1
177026    1
177027    1
177028    0
177029    1
177030    0
177031    1
177032    1
177033    1
177034    0
177035    0
177036    0
177037    1
177038    1
177039    1
177040    0
177041    0
177042    1
177043    1
177044    1
177045    0
177046    1
177047    1
177048    0
177049    0
177050    1
177051    0
177052    1
177053    1
177054    1
177055    0
177056    1
177057    1
177058    1
177059    0
177060    1
177061    1
177062    1
177063    1
177064    0
177065    0
Name: p1_action, dtype: int64, 41: 174010    1
174011    0
174012    0
174013    0
174014    1
174015    1
174016    1
174017    0
174018    0
174019    0
174020    1
174021    1
174022    1
174023    0
174024    0
174025    0
174026    0
174027    0
174028    0
174029    0
174030    0
174031    1
174032    1
174033    0
174034    0
174035    0
174036    1
174037    1
174038    1
174039    1
174040    0
174041    0
174042    0
174043    1
174044    1
174045    1
174046    0
174047    0
174048    0
174049    1
174050    1
174051    1
174052    0
174053    0
174054    0
174055    0
174056    0
174057    0
174058    0
174059    0
174060    0
174061    1
174062    1
174063    1
174064    0
174065    0
174066    0
174067    1
174068    1
174069    1
Name: p1_action, dtype: int64, 42: Series([], dtype: object), 43: 95118    0
Name: p1_action, dtype: int64, 44: Series([], dtype: object), 45: 162503    0
162504    1
162505    0
162506    0
162507    1
162508    0
162509    0
162510    1
162511    0
162512    0
162513    1
162514    0
162515    0
162516    1
162517    0
162518    0
162519    1
162520    1
162521    0
162522    0
162523    1
162524    0
162525    0
162526    1
162527    0
162528    1
162529    0
162530    0
162531    0
162532    1
162533    0
162534    1
162535    0
162536    0
162537    1
162538    0
162539    1
162540    0
162541    0
162542    0
162543    1
162544    0
162545    1
162546    0
162547    0
162548    0
162549    0
162550    1
162551    0
162552    1
162553    0
162554    0
162555    0
162556    1
162557    0
162558    1
Name: p1_action, dtype: int64, 46: 19604    0
Name: p1_action, dtype: int64, 47: 62685    0
Name: p1_action, dtype: int64, 48: 170885    1
170886    1
170887    1
170888    1
170889    0
170890    0
170891    1
170892    1
170893    1
170894    1
170895    1
170896    0
170897    0
170898    1
170899    1
170900    1
170901    1
170902    1
170903    0
170904    1
170905    0
170906    0
170907    0
170908    0
170909    0
170910    0
170911    0
170912    1
170913    1
170914    1
170915    0
170916    1
170917    1
170918    1
170919    0
170920    0
170921    0
170922    1
170923    1
170924    0
170925    0
170926    1
170927    0
170928    0
170929    1
170930    1
170931    1
170932    1
170933    0
170934    1
Name: p1_action, dtype: int64, 49: Series([], Name: p1_action, dtype: int64), 50: 1821    1
Name: p1_action, dtype: int64, 51: 58383    0
Name: p1_action, dtype: int64, 52: 170418    0
170419    0
Name: p1_action, dtype: int64, 53: 52597    0
Name: p1_action, dtype: int64, 54: 144764    1
Name: p1_action, dtype: int64, 55: 97542    0
Name: p1_action, dtype: int64, 56: 2978    0
2979    0
2980    0
Name: p1_action, dtype: int64, 57: 168285    1
168286    1
168287    1
168288    1
168289    1
168290    1
168291    1
168292    1
168293    0
168294    1
168295    1
168296    1
168297    1
168298    1
168299    1
168300    1
168301    1
168302    1
168303    1
168304    1
168305    1
168306    1
168307    1
168308    1
168309    0
168310    1
168311    1
168312    1
168313    1
168314    1
168315    1
168316    1
168317    1
168318    1
168319    1
168320    1
168321    1
168322    1
168323    1
168324    1
168325    1
168326    1
168327    1
168328    1
168329    1
168330    1
168331    1
168332    1
168333    1
168334    1
168335    1
168336    1
168337    1
168338    1
168339    1
Name: p1_action, dtype: int64, 58: 141076    0
141077    0
141078    0
141079    0
141080    0
141081    0
141082    0
Name: p1_action, dtype: int64, 59: 22433    1
Name: p1_action, dtype: int64, 60: 125570    0
125571    0
Name: p1_action, dtype: int64, 61: 158097    0
158098    0
158099    0
158100    1
158101    0
158102    0
158103    0
158104    1
158105    0
158106    0
158107    0
158108    1
158109    0
158110    0
158111    0
158112    1
158113    0
158114    0
Name: p1_action, dtype: int64, 62: 127    1
Name: p1_action, dtype: int64, 63: 4088    0
Name: p1_action, dtype: int64, 64: 149964    0
Name: p1_action, dtype: int64, 65: 18410    0
Name: p1_action, dtype: int64, 66: 175938    1
175939    0
175940    0
175941    1
175942    1
175943    0
175944    1
175945    1
175946    0
175947    1
175948    1
175949    1
175950    0
175951    0
175952    0
175953    1
175954    1
175955    1
175956    1
175957    1
175958    0
175959    0
175960    0
175961    1
175962    1
175963    1
175964    0
175965    0
175966    1
175967    0
175968    0
175969    1
175970    1
175971    0
175972    1
175973    0
175974    1
175975    0
175976    1
175977    1
175978    1
175979    0
175980    0
175981    1
175982    1
175983    0
Name: p1_action, dtype: int64, 67: 14713    0
Name: p1_action, dtype: int64, 68: 59477    1
Name: p1_action, dtype: int64, 69: 132514    0
Name: p1_action, dtype: int64, 70: 1151    0
Name: p1_action, dtype: int64, 71: 63106    1
Name: p1_action, dtype: int64, 72: 12098    0
12099    0
Name: p1_action, dtype: int64, 73: 127199    0
127200    0
127201    0
127202    0
Name: p1_action, dtype: int64, 74: 50686    0
Name: p1_action, dtype: int64, 75: 25484    1
Name: p1_action, dtype: int64, 76: 17337    1
Name: p1_action, dtype: int64, 77: 16700    0
Name: p1_action, dtype: int64, 78: 176757    0
176758    0
176759    0
176760    0
176761    0
176762    0
Name: p1_action, dtype: int64, 79: Series([], dtype: object), 80: 14451    0
Name: p1_action, dtype: int64, 81: 118030    0
Name: p1_action, dtype: int64, 82: 2742    0
Name: p1_action, dtype: int64, 83: 1388    1
1389    0
Name: p1_action, dtype: int64, 84: 105345    1
Name: p1_action, dtype: int64, 85: 28854    0
Name: p1_action, dtype: int64, 86: 95930    0
Name: p1_action, dtype: int64, 87: Series([], Name: p1_action, dtype: int64), 88: 95572    0
Name: p1_action, dtype: int64, 89: Series([], Name: p1_action, dtype: int64), 90: 117263    1
Name: p1_action, dtype: int64, 91: 35706    1
35707    1
Name: p1_action, dtype: int64, 92: Series([], Name: p1_action, dtype: int64), 93: 13397    0
Name: p1_action, dtype: int64, 94: 18722    0
18723    0
Name: p1_action, dtype: int64, 95: 171837    0
171838    0
171839    0
171840    0
171841    0
         ..
171896    0
171897    0
171898    0
171899    0
171900    0
Name: p1_action, Length: 64, dtype: int64, 96: 2150    0
Name: p1_action, dtype: int64, 97: 16888    0
Name: p1_action, dtype: int64, 98: Series([], Name: p1_action, dtype: int64), 99: 5828    0
5829    0
Name: p1_action, dtype: int64, 100: 129135    0
Name: p1_action, dtype: int64, 101: 121354    0
Name: p1_action, dtype: int64, 102: Series([], Name: p1_action, dtype: int64), 103: 26338    0
Name: p1_action, dtype: int64, 104: 20920    0
Name: p1_action, dtype: int64, 105: 21208    0
Name: p1_action, dtype: int64, 106: 6266    1
6267    0
Name: p1_action, dtype: int64, 107: 12612    0
Name: p1_action, dtype: int64, 108: 9072    1
Name: p1_action, dtype: int64, 109: 3720    1
Name: p1_action, dtype: int64, 110: 32271    1
32272    1
Name: p1_action, dtype: int64, 111: 17567    1
17568    1
Name: p1_action, dtype: int64, 112: 34205    1
34206    0
34207    0
Name: p1_action, dtype: int64, 113: 168455    0
168456    1
168457    1
168458    1
168459    1
168460    1
168461    1
168462    1
168463    1
168464    1
168465    1
168466    1
168467    1
168468    1
168469    1
168470    1
168471    0
168472    1
168473    1
168474    1
168475    1
168476    1
168477    1
168478    1
168479    1
168480    1
168481    1
168482    1
168483    1
168484    1
168485    1
168486    1
168487    1
168488    1
168489    1
168490    0
168491    1
168492    1
168493    1
168494    1
Name: p1_action, dtype: int64, 114: 19116    1
Name: p1_action, dtype: int64, 115: 1009    1
Name: p1_action, dtype: int64, 116: 120984    0
120985    0
120986    0
120987    0
120988    0
Name: p1_action, dtype: int64, 117: 5221    1
Name: p1_action, dtype: int64, 118: 3055    0
Name: p1_action, dtype: int64, 119: 120285    1
120286    0
120287    1
120288    1
120289    1
120290    1
120291    0
120292    0
120293    0
120294    0
120295    1
120296    1
120297    1
120298    1
120299    0
120300    1
120301    0
120302    1
120303    1
120304    1
120305    1
120306    0
120307    0
120308    0
120309    0
120310    1
120311    1
120312    1
120313    1
120314    0
120315    0
120316    0
120317    0
120318    1
120319    1
120320    1
120321    1
120322    0
120323    0
120324    1
120325    0
120326    1
120327    0
120328    0
120329    1
120330    1
120331    1
120332    1
120333    0
120334    0
120335    0
120336    0
120337    1
120338    1
Name: p1_action, dtype: int64, 120: Series([], Name: p1_action, dtype: int64), 121: 38197    0
38198    0
Name: p1_action, dtype: int64, 122: 165657    0
165658    0
165659    0
165660    0
165661    0
165662    0
165663    0
165664    0
165665    0
165666    1
165667    1
165668    1
165669    1
165670    0
165671    0
165672    0
165673    0
165674    0
165675    0
165676    0
165677    0
165678    1
165679    1
165680    0
165681    0
165682    0
165683    0
165684    1
165685    0
165686    0
165687    0
165688    0
165689    1
165690    0
165691    0
165692    0
165693    0
165694    0
165695    0
165696    0
165697    0
165698    1
165699    1
165700    0
165701    0
165702    0
165703    0
165704    0
165705    0
165706    0
165707    0
165708    1
165709    1
165710    0
165711    0
165712    0
165713    0
Name: p1_action, dtype: int64, 123: 171530    1
Name: p1_action, dtype: int64, 124: Series([], dtype: object), 125: 11015    1
Name: p1_action, dtype: int64, 126: 9493    0
Name: p1_action, dtype: int64, 127: 7661    0
Name: p1_action, dtype: int64, 128: 102627    0
102628    0
102629    0
102630    0
Name: p1_action, dtype: int64, 129: 9786    1
Name: p1_action, dtype: int64, 130: 116697    1
116698    0
Name: p1_action, dtype: int64, 131: 5601    0
Name: p1_action, dtype: int64, 132: 23219    1
Name: p1_action, dtype: int64, 133: 6756    0
6757    0
6758    0
Name: p1_action, dtype: int64, 134: 117330    0
Name: p1_action, dtype: int64, 135: Series([], Name: p1_action, dtype: int64), 136: 156173    1
156174    1
156175    1
156176    1
156177    1
         ..
156239    0
156240    1
156241    1
156242    1
156243    1
Name: p1_action, Length: 71, dtype: int64, 137: 2097    0
2098    0
Name: p1_action, dtype: int64, 138: 5111    0
5112    0
Name: p1_action, dtype: int64, 139: 180259    1
180260    0
180261    0
180262    0
180263    0
         ..
180333    0
180334    0
180335    0
180336    0
180337    1
Name: p2_action, Length: 79, dtype: int64, 140: 6950    1
6951    1
6952    1
Name: p1_action, dtype: int64, 141: Series([], Name: p1_action, dtype: int64), 142: 91983    0
Name: p1_action, dtype: int64, 143: 3234    1
Name: p1_action, dtype: int64, 144: 81450    0
81451    0
81452    0
Name: p1_action, dtype: int64, 145: 4909    0
Name: p1_action, dtype: int64, 146: 127149    0
Name: p1_action, dtype: int64, 147: Series([], Name: p1_action, dtype: int64), 148: 178469    0
178470    0
178471    0
178472    0
178473    0
         ..
178529    0
178530    1
178531    1
178532    1
178533    1
Name: p1_action, Length: 65, dtype: int64, 149: 2787    0
2788    0
Name: p1_action, dtype: int64, 150: 22053    0
22054    0
Name: p1_action, dtype: int64, 151: Series([], Name: p1_action, dtype: int64), 152: 7489    0
7490    0
7491    0
7492    0
7493    0
7494    0
7495    0
Name: p1_action, dtype: int64, 153: 851    1
Name: p1_action, dtype: int64, 154: 1272    0
Name: p1_action, dtype: int64, 155: 162308    1
Name: p1_action, dtype: int64, 156: 61543    1
Name: p1_action, dtype: int64, 157: 73841    0
Name: p1_action, dtype: int64, 158: 9697    1
Name: p1_action, dtype: int64, 159: 17401    0
17402    1
17403    0
Name: p1_action, dtype: int64, 160: 124597    0
Name: p1_action, dtype: int64, 161: Series([], dtype: object), 162: 171710    1
171711    0
171712    0
171713    0
171714    0
         ..
171773    0
171774    1
171775    1
171776    1
171777    1
Name: p1_action, Length: 68, dtype: int64, 163: 136691    1
136692    0
136693    0
136694    0
136695    1
136696    1
Name: p1_action, dtype: int64, 164: 111956    1
111957    0
Name: p1_action, dtype: int64, 165: 115725    0
Name: p1_action, dtype: int64, 166: 7433    0
7434    0
Name: p1_action, dtype: int64, 167: 137428    0
Name: p1_action, dtype: int64, 168: 6392    0
6393    0
6394    0
6395    0
6396    0
Name: p1_action, dtype: int64, 169: 135612    0
135613    0
135614    0
135615    0
135616    0
135617    0
135618    0
Name: p1_action, dtype: int64, 170: Series([], Name: p1_action, dtype: int64), 171: 64335    0
Name: p1_action, dtype: int64, 172: 16497    1
16498    1
Name: p1_action, dtype: int64, 173: 28685    1
Name: p1_action, dtype: int64, 174: 178916    0
178917    0
178918    0
178919    0
178920    0
178921    0
178922    0
178923    0
178924    0
178925    0
178926    0
178927    0
178928    0
178929    0
178930    0
178931    0
178932    0
178933    1
178934    1
178935    1
178936    1
178937    1
178938    1
178939    1
178940    1
178941    1
178942    1
178943    1
178944    1
178945    1
178946    1
178947    1
178948    1
178949    1
178950    1
178951    1
178952    1
178953    1
178954    1
178955    1
178956    1
178957    1
178958    1
178959    1
178960    1
178961    1
178962    1
178963    1
178964    1
178965    1
178966    1
178967    1
178968    1
178969    1
178970    1
178971    1
178972    1
178973    1
Name: p1_action, dtype: int64, 175: 13905    0
Name: p1_action, dtype: int64, 176: 104644    0
Name: p1_action, dtype: int64, 177: 166826    0
166827    0
166828    0
166829    0
166830    0
         ..
166887    0
166888    0
166889    0
166890    0
166891    0
Name: p1_action, Length: 66, dtype: int64, 178: 4205    0
Name: p1_action, dtype: int64, 179: 91000    0
Name: p1_action, dtype: int64, 180: 15166    0
Name: p1_action, dtype: int64, 181: 160680    0
160681    0
160682    0
160683    0
160684    0
Name: p1_action, dtype: int64, 182: 43423    0
43424    0
43425    0
Name: p1_action, dtype: int64, 183: 103179    1
Name: p1_action, dtype: int64, 184: 179094    0
179095    0
179096    0
179097    1
179098    1
         ..
179152    1
179153    1
179154    0
179155    0
179156    1
Name: p1_action, Length: 63, dtype: int64, 185: 117874    0
117875    0
117876    0
117877    0
117878    0
117879    0
117880    0
117881    0
Name: p1_action, dtype: int64, 186: 12786    0
12787    0
12788    0
12789    1
12790    0
12791    0
12792    0
Name: p1_action, dtype: int64, 187: 10221    1
Name: p1_action, dtype: int64, 188: 163813    0
163814    0
163815    0
163816    0
163817    0
163818    0
163819    0
163820    0
163821    0
163822    0
Name: p1_action, dtype: int64, 189: 24004    0
Name: p1_action, dtype: int64, 190: 69038    0
69039    0
Name: p1_action, dtype: int64, 191: 20794    0
20795    0
20796    0
20797    1
20798    0
20799    0
20800    0
Name: p1_action, dtype: int64, 192: 11723    0
Name: p1_action, dtype: int64, 193: 99182    0
99183    0
99184    0
Name: p1_action, dtype: int64, 194: 14511    0
Name: p1_action, dtype: int64, 195: 139512    0
Name: p1_action, dtype: int64, 196: 22155    0
22156    0
22157    0
22158    1
22159    0
22160    0
22161    0
22162    1
22163    0
Name: p1_action, dtype: int64, 197: 165313    0
165314    0
165315    0
165316    1
165317    1
         ..
165386    1
165387    1
165388    1
165389    1
165390    1
Name: p1_action, Length: 78, dtype: int64, 198: 173539    1
173540    0
173541    0
173542    0
173543    1
173544    1
173545    1
173546    0
173547    0
173548    0
173549    1
173550    1
173551    1
173552    0
173553    0
173554    0
173555    1
173556    1
173557    1
173558    0
173559    0
173560    0
173561    0
173562    0
173563    1
173564    1
173565    0
173566    0
173567    1
173568    1
173569    1
173570    0
173571    0
173572    0
173573    1
173574    1
173575    1
173576    0
173577    0
173578    0

In [4]:
player_prefix_dict[13]

24362    0
24363    0
24364    0
24365    0
Name: p1_action, dtype: int64

In [5]:

modified = {}

for player_id in range(1,201):
    series = player_prefix_dict[player_id]
    prefix = ""
    for i in range(len(series)):
        prefix += str(series.iloc[i])

    if prefix not in modified:
        modified[prefix] = []

    modified[prefix].append(player_id)

print(modified)

{'1': [1, 5, 7, 19, 27, 39, 50, 54, 59, 62, 68, 71, 75, 76, 84, 90, 108, 109, 114, 115, 117, 123, 125, 129, 132, 143, 153, 155, 156, 158, 173, 183, 187], '00': [2, 6, 31, 52, 60, 72, 94, 99, 121, 137, 138, 149, 150, 166, 190], '0': [3, 14, 16, 18, 20, 22, 23, 35, 37, 38, 43, 46, 47, 51, 53, 55, 63, 64, 65, 67, 69, 70, 74, 77, 80, 81, 82, 85, 86, 88, 93, 96, 97, 100, 101, 103, 104, 105, 107, 118, 126, 127, 131, 134, 142, 145, 146, 154, 157, 160, 165, 167, 171, 175, 176, 178, 179, 180, 189, 192, 194, 195, 199, 200], '11111': [4, 15], '0001000100010': [8], '00000000000000': [9], '100001111011110000111111100000111100011110000110111': [10], '10': [11, 83, 106, 130, 164], '': [12, 26, 29, 42, 44, 49, 79, 87, 89, 92, 98, 102, 120, 124, 135, 141, 147, 151, 161, 170], '0000': [13, 73, 128], '011': [17], '111': [21, 140], '11': [24, 25, 32, 91, 110, 111, 172], '100001111': [28], '000': [30, 56, 133, 144, 182, 193], '11111111111': [33], '000000000000000000000001111111110000000000000000011111111111111111111111': [34], '01': [36], '0010100110101100011101011100011100111011001011101110111100': [40], '100011100011100000000110001111000111000111000000000111000111': [41], '01001001001001001100100101000101001010001010000101000101': [45], '11110011111001111101000000011101110001100100111101': [48], '1111111101111111111111110111111111111111111111111111111': [57], '0000000': [58, 152, 169], '000100010001000100': [61], '1001101101110001111100011100100110101011100110': [66], '000000': [78], '0000000000000000000010000000000000000000100000000000000000000000': [95], '100': [112], '0111111111111111011111111111111111101111': [113], '00000': [116, 168, 181], '101111000011110101111000011110000111100101001111000011': [119], '000000000111100000000110000100001000000001100000000110000': [122], '11111111111111111111111110111111111111111111111111111111111111111101111': [136], '1000000111100001111000011100000100011111110000111100001110000011110000111100001': [139], '00000000000010111111111111111111111011111111111111110110111101111': [148], '010': [159], '10000000000000000000000000000000000000001111111111111111111111101111': [162], '100011': [163], '0000000000000000011111111111111111111111111111111111111111': [174], '000000000000110110110110110110101101101101011011011011011011000000': [177], '000110000101000011001100100110110010101010111101100110111011001': [184], '00000000': [185], '0001000': [186, 191], '0000000000': [188], '000100010': [196], '000111111111111111111011111111111111111111110110111111011101111111111111111111': [197], '1000111000111000111000001100111000111000111000111100011': [198]}

In [6]:
temp = df[df['p1_id'] == 9]

for i in range(3014):
    game_data = temp[temp['game_id'] == i]

    if(game_data.empty):
        continue
    else:
        print(game_data)

       game_id  p1_id  p2_id  p1_action  p2_action  turn
69782     1167      9     25          0          1     1
69783     1167      9     25          0          1     2
69784     1167      9     25          0          1     3
69785     1167      9     25          0          1     4
69786     1167      9     25          0          1     5
...        ...    ...    ...        ...        ...   ...
69849     1167      9     25          0          1    68
69850     1167      9     25          0          1    69
69851     1167      9     25          0          1    70
69852     1167      9     25          0          1    71
69853     1167      9     25          0          1    72

[72 rows x 6 columns]
        game_id  p1_id  p2_id  p1_action  p2_action  turn
124746     2097      9     45          0          0     1
124747     2097      9     45          0          0     2
124748     2097      9     45          0          0     3
124749     2097      9     45          0          0     4
124750     2097      9     45          0          0     5
124751     2097      9     45          0          0     6
124752     2097      9     45          0          1     7
124753     2097      9     45          0          0     8
124754     2097      9     45          0          0     9
124755     2097      9     45          0          0    10
124756     2097      9     45          0          0    11
124757     2097      9     45          0          0    12
124758     2097      9     45          0          0    13
124759     2097      9     45          0          0    14
124760     2097      9     45          1          1    15
124761     2097      9     45          0          0    16
124762     2097      9     45          0          0    17
124763     2097      9     45          1          0    18
124764     2097      9     45          0          1    19
124765     2097      9     45          0          0    20
124766     2097      9     45          0          0    21
124767     2097      9     45          0          0    22
124768     2097      9     45          0          0    23
124769     2097      9     45          1          0    24
124770     2097      9     45          0          1    25
124771     2097      9     45          0          0    26
124772     2097      9     45          0          0    27
124773     2097      9     45          0          0    28
124774     2097      9     45          0          0    29
124775     2097      9     45          0          0    30
124776     2097      9     45          0          0    31
124777     2097      9     45          0          0    32
124778     2097      9     45          0          0    33
124779     2097      9     45          0          0    34
124780     2097      9     45          1          0    35
124781     2097      9     45          0          1    36
124782     2097      9     45          0          0    37
124783     2097      9     45          0          0    38
124784     2097      9     45          0          0    39
124785     2097      9     45          0          0    40
124786     2097      9     45          0          0    41
124787     2097      9     45          0          0    42
124788     2097      9     45          1          0    43
124789     2097      9     45          0          1    44
124790     2097      9     45          0          0    45
124791     2097      9     45          0          0    46
124792     2097      9     45          0          0    47
124793     2097      9     45          0          0    48
124794     2097      9     45          0          0    49
124795     2097      9     45          0          0    50
124796     2097      9     45          0          0    51
124797     2097      9     45          0          0    52
124798     2097      9     45          0          0    53
124799     2097      9     45          0          0    54
124800     2097      9     45          0          0    55
124801     2097      9     45          0          0    56
        game_id  p1_id  p2_id  p1_action  p2_action  turn
135497     2273      9    200          0          0     1
135498     2273      9    200          0          0     2
135499     2273      9    200          0          0     3
135500     2273      9    200          0          0     4
135501     2273      9    200          0          0     5
135502     2273      9    200          0          0     6
135503     2273      9    200          0          0     7
135504     2273      9    200          0          0     8
135505     2273      9    200          0          0     9
135506     2273      9    200          0          0    10
135507     2273      9    200          0          0    11
135508     2273      9    200          0          0    12
135509     2273      9    200          0          0    13
135510     2273      9    200          0          0    14
135511     2273      9    200          0          0    15
135512     2273      9    200          0          0    16
135513     2273      9    200          1          0    17
135514     2273      9    200          0          0    18
135515     2273      9    200          0          0    19
135516     2273      9    200          0          0    20
135517     2273      9    200          0          0    21
135518     2273      9    200          0          0    22
135519     2273      9    200          0          0    23
135520     2273      9    200          0          0    24
135521     2273      9    200          0          0    25
135522     2273      9    200          0          0    26
135523     2273      9    200          0          0    27
135524     2273      9    200          1          0    28
135525     2273      9    200          0          0    29
135526     2273      9    200          0          0    30
135527     2273      9    200          0          0    31
135528     2273      9    200          0          0    32
135529     2273      9    200          0          0    33
135530     2273      9    200          0          0    34
135531     2273      9    200          0          0    35
135532     2273      9    200          0          0    36
135533     2273      9    200          0          0    37
135534     2273      9    200          0          0    38
135535     2273      9    200          0          0    39
135536     2273      9    200          0          0    40
135537     2273      9    200          0          0    41
135538     2273      9    200          0          0    42
135539     2273      9    200          0          0    43
135540     2273      9    200          0          0    44
135541     2273      9    200          0          0    45
135542     2273      9    200          0          0    46
135543     2273      9    200          0          0    47
135544     2273      9    200          0          0    48
135545     2273      9    200          0          0    49
135546     2273      9    200          0          0    50
135547     2273      9    200          0          0    51
135548     2273      9    200          0          0    52
135549     2273      9    200          0          0    53
        game_id  p1_id  p2_id  p1_action  p2_action  turn
177475     2968      9     36          0          0     1
177476     2968      9     36          0          0     2
177477     2968      9     36          0          0     3
177478     2968      9     36          0          0     4
177479     2968      9     36          0          0     5
177480     2968      9     36          0          0     6
177481     2968      9     36          0          0     7
177482     2968      9     36          0          0     8
177483     2968      9     36          0          0     9
177484     2968      9     36          0          0    10
177485     2968      9     36          0          0    11
177486     2968      9     36          0          0    12
177487     2968      9     36          0          0    13
177488     2968      9     36          0          0    14
177489     2968      9     36          0          0    15
177490     2968      9     36          0          0    16
177491     2968      9     36          0          0    17
177492     2968      9     36          0          0    18
177493     2968      9     36          1          0    19
177494     2968      9     36          0          0    20
177495     2968      9     36          1          0    21
177496     2968      9     36          0          0    22
177497     2968      9     36          0          0    23
177498     2968      9     36          0          0    24
177499     2968      9     36          0          0    25
177500     2968      9     36          0          0    26
177501     2968      9     36          0          0    27
177502     2968      9     36          0          0    28
177503     2968      9     36          0          0    29
177504     2968      9     36          0          0    30
177505     2968      9     36          0          0    31
177506     2968      9     36          0          0    32
177507     2968      9     36          0          0    33
177508     2968      9     36          0          0    34
177509     2968      9     36          0          1    35
177510     2968      9     36          0          0    36
177511     2968      9     36          0          0    37
177512     2968      9     36          0          0    38
177513     2968      9     36          0          1    39
177514     2968      9     36          0          0    40
177515     2968      9     36          1          1    41
177516     2968      9     36          0          1    42
177517     2968      9     36          0          0    43
177518     2968      9     36          0          0    44
177519     2968      9     36          0          0    45
177520     2968      9     36          0          0    46
177521     2968      9     36          0          0    47
177522     2968      9     36          0          0    48
177523     2968      9     36          0          0    49

In [8]:
strategy_dict = {} # key is a tuple containing the gameid, player1 id and player2 id

for i in range(2):
    game_data = df[df['game_id'] == i]
    
    if game_data.empty:
        continue

    key_player1 = (i,game_data.iloc[0]['p1_id'])
    key_player2 = (i,game_data.iloc[0]['p2_id'])

    p1_cheat_count = 0
    p2_cheat_count = 0

    p1_cheat_count_list = []
    p2_cheat_count_list = []

    cheats_in_window_p1 = {} #dictionary of dictionaries
    cheats_in_window_p2 = {}

    cheats_in_window_p1[0] = {}
    cheats_in_window_p2[0] = {}

    if game_data.iloc[0]['p1_action'] == "CHEAT":
            p1_cheat_count+=1
            p1_cheat_count_list.append(p1_cheat_count)
    else:
        p1_cheat_count_list.append(p1_cheat_count)

    if game_data.iloc[0]['p2_action'] == "CHEAT":
        p2_cheat_count+=1
        p2_cheat_count_list.append(p2_cheat_count)
    else:
        p2_cheat_count_list.append(p1_cheat_count)

    cheats_in_window_p1[1] = {1:p1_cheat_count}
    cheats_in_window_p2[1] = {1:p2_cheat_count}

    if game_data.iloc[1]['p1_action'] == "CHEAT":
            p1_cheat_count+=1
            p1_cheat_count_list.append(p1_cheat_count)
    else:
        p1_cheat_count_list.append(p1_cheat_count)

    if game_data.iloc[1]['p2_action'] == "CHEAT":
        p2_cheat_count+=1
        p2_cheat_count_list.append(p2_cheat_count)
    else:
        p2_cheat_count_list.append(p1_cheat_count)


    for index, row in game_data.iterrows():

        if(index == 0 or index == 1):
            continue

        cheats_in_window_p1[index] = {(index - i): (p1_cheat_count - p1_cheat_count_list[i-1]) for i in range(1,index)}
        cheats_in_window_p1[index][index] = p1_cheat_count

        cheats_in_window_p2[index] = {(index - i): (p2_cheat_count - p2_cheat_count_list[i-1]) for i in range(1,index)}
        cheats_in_window_p2[index][index] = p2_cheat_count

        #updating cheat counts
        if row['p1_action'] == "CHEAT":
            p1_cheat_count+=1
            p1_cheat_count_list.append(p1_cheat_count)
        else:
            p1_cheat_count_list.append(p1_cheat_count)

        if row['p2_action'] == "CHEAT":
            p2_cheat_count+=1
            p2_cheat_count_list.append(p2_cheat_count)
        else:
            p2_cheat_count_list.append(p1_cheat_count)

    
    #stores in format own and other
    strategy_dict[key_player1] = [cheats_in_window_p1,cheats_in_window_p2]
    strategy_dict[key_player2] = [cheats_in_window_p2,cheats_in_window_p1]

print(strategy_dict)

IndexError: list index out of range

This was to split the data based on common prefixes and then apply some sort of common window approach tracking number of cheats to distinguish between strategies.
Couldnt finish this.

In [9]:
correlation_matrix = np.full((201,201),-1)

player_game_data_dict = {}

for player_id in range(2):

    gds = []

    temp1 = df[df['p1_id'] == player_id]
    temp2 = df[df['p2_id'] == player_id]

    for game_id in range(3014):

        game_data1 = temp1[temp1['game_id'] == game_id]
        game_data2 = temp2[temp2['game_id'] == game_id]

        if(game_data1.empty and game_data2.empty):
            continue
        elif game_data1.empty:
            gds.append(game_data2)
        elif game_data2.empty:
            gds.append(game_data1)
        else:
            gds.append(game_data1)
            gds.append(game_data2)

    player_game_data_dict[player_id] = gds

for player_id in range(2):

    gds = player_game_data_dict[player_id]

    for gd in gds:
        correlation = np.corrcoef(gd["p1_action"],(gd["p2_action"]))[0][1]
        p1_id = gd["p1_id"].iloc[0] - 1
        p2_id = gd["p2_id"].iloc[0] - 1
        if(np.isnan(correlation)):
            correlation = 0

        correlation_matrix[p1_id, p2_id] = correlation

C:\Users\vedch\AppData\Roaming\Python\Python311\site-packages\numpy\lib\function_base.py:2853: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\vedch\AppData\Roaming\Python\Python311\site-packages\numpy\lib\function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

another approach was with correlations which also we couldn't get to work.